let inputData = [
  [
    { number: 01 },
    { workingTitle: "zest" },
    { demo: 0 },
    { guitar: 0 },
    { bass: 0 },
    { drums: 0 },
    { synths: 0 },
    { fx: 0 },
    { mix: 0 },
    { master: 0 },
    { done: 0 },
  ],
  [
    { number: 02 },
    { workingTitle: "test" },
    { demo: 0 },
    { guitar: 0 },
    { bass: 0 },
    { drums: 0 },
    { synths: 0 },
    { fx: 0 },
    { mix: 0 },
    { master: 0 },
    { done: 0 },
  ],
  [
    { number: 03 },
    { workingTitle: "rest" },
    { demo: 0 },
    { guitar: 0 },
    { bass: 0 },
    { drums: 0 },
    { synths: 0 },
    { fx: 0 },
    { mix: 0 },
    { master: 0 },
    { done: 0 },
  ],
  [
    { number: 04 },
    { workingTitle: "fest" },
    { demo: 0 },
    { guitar: 0 },
    { bass: 0 },
    { drums: 0 },
    { synths: 0 },
    { fx: 0 },
    { mix: 0 },
    { master: 0 },
    { done: 0 },
  ],
  [
    { number: 05 },
    { workingTitle: "best" },
    { demo: 0 },
    { guitar: 0 },
    { bass: 0 },
    { drums: 0 },
    { synths: 0 },
    { fx: 0 },
    { mix: 0 },
    { master: 0 },
    { done: 0 },
  ],
];
