let inputData = [
  [
    { title: "&#8287; number" },
    { title: "&#8287; working </ br> &#8287; &#8287; title" },
    { title: "&#8287; &#8287; demo" },
    { title: "&#8287; guitar" },
    { title: "&#8287; bass" },
    { title: "&#8287; drums" },
    { title: "&#8287; synths" },
    { title: "&#8287; fx" },
    { title: "&#8287; mix" },
    { title: "&#8287; master" },
    { title: "&#8287; done" },
  ],
  [
    { number: "01" },
    { workingTitle: "Katie's Cool" },
    { demo: "2" },
    { guitar: "2" },
    { bass: "0" },
    { drums: "3" },
    { synths: "0" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "02" },
    { workingTitle: "test" },
    { demo: "1" },
    { guitar: "3" },
    { bass: "1" },
    { drums: "4" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "03" },
    { workingTitle: "rest" },
    { demo: "1" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "04" },
    { workingTitle: "fest" },
    { demo: "1" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "05" },
    { workingTitle: "best" },
    { demo: "1" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
];
