let inputData = [
  [
    { title: "number" },
    { title: "title" },
    { title: "demo" },
    { title: "guitar" },
    { title: "bass" },
    { title: "drums" },
    { title: "synths" },
    { title: "fx" },
    { title: "mix" },
    { title: "master" },
    { title: "done" },
  ],
  [
    { number: "01" },
    { workingTitle: "gc" },
    { demo: "2" },
    { guitar: "0" },
    { bass: "0" },
    { drums: "0" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "02" },
    { workingTitle: "cove(n)" },
    { demo: "2" },
    { guitar: "0" },
    { bass: "2" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "03" },
    { workingTitle: "arnold" },
    { demo: "2" },
    { guitar: "1" },
    { bass: "2" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "04" },
    { workingTitle: "yuzu" },
    { demo: "2" },
    { guitar: "2" },
    { bass: "1" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "05" },
    { workingTitle: "slap" },
    { demo: "2" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "06" },
    { workingTitle: "ole" },
    { demo: "2" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "2" },
    { synths: "1" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "07" },
    { workingTitle: "se7en" },
    { demo: "2" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "08" },
    { workingTitle: "e1ght" },
    { demo: "2" },
    { guitar: "0" },
    { bass: "0" },
    { drums: "0" },
    { synths: "2" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "09" },
    { workingTitle: "A A N E" },
    { demo: "2" },
    { guitar: "0" },
    { bass: "1" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "RPM01" },
    { workingTitle: "RPM01" },
    { demo: "2" },
    { guitar: "0" },
    { bass: "1" },
    { drums: "2" },
    { synths: "2" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
  [
    { number: "RPM02" },
    { workingTitle: "RPM02" },
    { demo: "2" },
    { guitar: "0" },
    { bass: "0" },
    { drums: "2" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "0" },
  ],
];
