let inputData = [
  [
    { title: "number" },
    { title: "title" },
    { title: "demo" },
    { title: "guitar" },
    { title: "bass" },
    { title: "drums" },
    { title: "synths" },
    { title: "fx" },
    { title: "mix" },
    { title: "master" },
    { title: "done" },
  ],
  [
    { number: "01" },
    { workingTitle: "zest" },
    { demo: "2" },
    { guitar: "2" },
    { bass: "0" },
    { drums: "3" },
    { synths: "0" },
    { fx: "2" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "02" },
    { workingTitle: "test" },
    { demo: "1" },
    { guitar: "3" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "03" },
    { workingTitle: "rest" },
    { demo: "1" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "04" },
    { workingTitle: "fest" },
    { demo: "1" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
  [
    { number: "05" },
    { workingTitle: "best" },
    { demo: "1" },
    { guitar: "1" },
    { bass: "1" },
    { drums: "1" },
    { synths: "1" },
    { fx: "1" },
    { mix: "1" },
    { master: "1" },
    { done: "1" },
  ],
];
